### ISSUE TITLE
tom-selectを導入したい

### ISSUE THREAD

**Issue by yasu575** [yasu575/zuboramen#57]
・質問内容・実現したいこと
tom-selectを導入したいです

・発生している問題
インクリメンタルサーチを実装中で、tom-selectを使いたいのですが、うまく導入されずに詰まっています。自分なりに調べていろいろと試してみましたが、原因を特定できない状態です。

現在このようなエラーがでております。
[![Image from Gyazo](https://i.gyazo.com/0533b45268c69e4a3612d67d0f38917e.png)](https://gyazo.com/0533b45268c69e4a3612d67d0f38917e)
[![Image from Gyazo](https://i.gyazo.com/12509ac51e65d63d571a2f73c34168fd.png)](https://gyazo.com/12509ac51e65d63d571a2f73c34168fd)

環境
Rails 7.0.4
Ruby 3.2.2

・どこまでできているか
```
yarn add tom-select
```
と打ち込み、yarnでtom-selectを追加し、tom-selectのcssをインポートするために、
app/assets/stylesheets/application.scss
```
@import "tom-select/dist/css/tom-select.bootstrap5";
```
を打ち込んだらエラーとなってしまいました。

・試したこと
https://qiita.com/kazutosato/items/1ae1cf0ec380a75d4dc4
https://qiita.com/ko_coon/items/2658fab30a9b36f16665

アドバイスをよろしくお願いします。

・参考記事
https://qiita.com/takuya-s/items/49975d70ca0fbc27ae9a

**Comment by Tsuchiya2** [comment]
そうですね。。情報が少ないので難しいですが。。。

```
まず、yarnで正しくtom-selectがインストールされたか確認してみましょう。プロジェクトのnode_modulesディレクトリ内にtom-selectディレクトリが存在するか確認してください。もし存在しなければ、インストールが完全に行われていない可能性があります。その場合は再度yarn add tom-selectを実行してみてください。

node_modulesにtom-selectディレクトリが存在し、dist/cssディレクトリ内にtom-select.bootstrap5.cssが存在することを確認してください。ファイル名やパスに誤りがないか確認しましょう。

@import "tom-select/dist/css/tom-select.bootstrap5";を書いておりますが、node_modulesディレクトリを読み込む設定になっているのか確認しましょう。
```

一旦上記確認をお願いできますでしょうか。

**Comment by yasu575** [comment]
node_modulesにtom-selectディレクトリが存在し、dist/cssディレクトリ内にtom-select.bootstrap5.cssが存在することを確認しました。下記の通りになります。こちらエラーになっているのですが、そういうものなのでしょうか？
[![Image from Gyazo](https://i.gyazo.com/2493c142da999713e06766e085ebd8da.png)](https://gyazo.com/2493c142da999713e06766e085ebd8da)

>@import "tom-select/dist/css/tom-select.bootstrap5";を書いておりますが、node_modulesディレクトリを読み込む設定になっているのか確認しましょう。

@import "tom-select/dist/css/tom-select.bootstrap5.css";と記載するとエラーは解決しますが、インクリメンタルサーチが実装できません。これはコードがおかしいということなのでしょうか？

**Comment by Tsuchiya2** [comment]
エラーが出てないということは読み込みは問題ないということかと思うので、公式ドキュメントを参照して実装に取り組んでみましょう。

**Comment by yasu575** [comment]
わかりました。ありがとうございました！
