### ISSUE TITLE
インクリメンタルサーチを実装したい

### ISSUE THREAD

**Issue by yasu575** [yasu575/zuboramen#58]
- 質問内容・実現したいこと
インクリメンタルサーチを実装したい
フォーム内でセレクトしかできず、入力することができないため、tom-selectでインクリメンタルサーチを実装し、入力するたびに候補を表示させたい

- 現状発生している問題・エラーメッセージ
[![Image from Gyazo](https://i.gyazo.com/a39305779eb1038a7c0cb5a4d3d0f054.png)](https://gyazo.com/a39305779eb1038a7c0cb5a4d3d0f054)

- どの処理までうまく動いているのか
tom-selectを導入するところまでできています。

- 該当のソースコード
app/assets/stylesheets/application.scss
```
@import "tom-select/dist/css/tom-select.bootstrap5.css";
```

app/javascript/controllers/select-controller.js
```
import { Controller } from "@hotwired/stimulus"
import TomSelect from "tom-select"

// Connects to data-controller="select"
export default class extends Controller {
  connect() {
    new TomSelect('#select',{
      create: true,
      sortField: {
        field: "text",
        direction: "asc"
      },
    });
  }
}
```

app/views/posts/_form.html.erb
```
<div class="form-group text-center mb-3">
    <%= f.label :title %>
    <span class="badge text-bg-danger">必須</span>
    <%= f.collection_select :title, Noodle.all, :name, :name, { include_blank: '商品名を検索してください' }, { class: 'form-control', data: { controller: "select" } } %>
</div>
```

app/javascript/controllers/index.js
```
// Import and register all your controllers from the importmap under controllers/*

import { application } from "controllers/application"

import SelectController from "./select_controller"
application.register("select", SelectController)

// Eager load all controllers defined in the import map under controllers/**/*_controller
import { eagerLoadControllersFrom } from "@hotwired/stimulus-loading"
eagerLoadControllersFrom("controllers", application)

// Lazy load controllers as they appear in the DOM (remember not to preload controllers in import map!)
// import { lazyLoadControllersFrom } from "@hotwired/stimulus-loading"
// lazyLoadControllersFrom("controllers", application)
```

- エラーから考えられる原因
@import "tom-select/dist/css/tom-select.bootstrap5.css";をうまく読み込めていない

- 参考記事
https://qiita.com/peco4107/items/6c8fba1a13c54a5447a7
https://tom-select.js.org/examples/
https://qiita.com/takuya-s/items/49975d70ca0fbc27ae9a

アドバイスをよろしくお願いします。

**Comment by Tsuchiya2** [comment]
Rails.application.config.assets.pathsにnode_modulesを加えるようになっているか確認してみましょう。

**Comment by yasu575** [comment]
すみません、それはどう確認するのですか？
わからないなりに下記のように自分で調べて確認してみたのですが、これであっていますか？


config/initializers/assets.rb
```
# Be sure to restart your server when you modify this file.

# Version of your assets, change this if you want to expire all your assets.
Rails.application.config.assets.version = "1.0"

# Add additional assets to the asset load path.
# Rails.application.config.assets.paths << Emoji.images_path

# Precompile additional assets.
# application.js, application.css, and all non-JS/CSS in the app/assets
# folder are already added.
# Rails.application.config.assets.precompile += %w( admin.js admin.css )
```

```
irb(main):001:0> Rails.application.config.assets.paths
=> 
["/Users/inabayasushiakira/portfolio/zuboramen/app/assets/config",
 "/Users/inabayasushiakira/portfolio/zuboramen/app/assets/images",
 "/Users/inabayasushiakira/portfolio/zuboramen/app/assets/javascripts",
 "/Users/inabayasushiakira/portfolio/zuboramen/app/assets/stylesheets",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/jquery-rails-4.5.1/vendor/assets/javascripts",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/stimulus-rails-1.2.1/app/assets/javascripts",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/turbo-rails-1.4.0/app/assets/javascripts",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/importmap-rails-1.1.6/app/assets/javascripts",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actioncable-7.0.4.3/app/assets/javascripts",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actiontext-7.0.4.3/app/assets/javascripts",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actiontext-7.0.4.3/app/assets/stylesheets",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activestorage-7.0.4.3/app/assets/javascripts",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionview-7.0.4.3/lib/assets/compiled",
 #<Pathname:/Users/inabayasushiakira/portfolio/zuboramen/app/javascript>,
 #<Pathname:/Users/inabayasushiakira/portfolio/zuboramen/vendor/javascript>,
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/popper_js-2.11.7/assets/javascripts",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootstrap-5.2.3/assets/stylesheets",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootstrap-5.2.3/assets/javascripts"]
```

**Comment by Tsuchiya2** [comment]
Rails基礎で作成したアプリケーションとかも参考にしてみると、現状とどう違うかが確認できると思います。

該当箇所の差分（現状とRails基礎）を見てみると良いかもしれません。

**Comment by yasu575** [comment]
config/initializers/assets.rbに下記のコードを追加しました。なにもかわらなかったです。

```
Rails.application.config.assets.paths << Rails.root.join('node_modules')
```

```
irb(main):004:0> Rails.application.config.assets.paths
=> 
["/Users/inabayasushiakira/portfolio/zuboramen/app/assets/config",                           
 "/Users/inabayasushiakira/portfolio/zuboramen/app/assets/images",                           
 "/Users/inabayasushiakira/portfolio/zuboramen/app/assets/javascripts",                      
 "/Users/inabayasushiakira/portfolio/zuboramen/app/assets/stylesheets",                      
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/jquery-rails-4.5.1/vendor/assets/javascripts",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/stimulus-rails-1.2.1/app/assets/javascripts",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/turbo-rails-1.4.0/app/assets/javascripts",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/importmap-rails-1.1.6/app/assets/javascripts",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actioncable-7.0.4.3/app/assets/javascripts",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actiontext-7.0.4.3/app/assets/javascripts",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actiontext-7.0.4.3/app/assets/stylesheets",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activestorage-7.0.4.3/app/assets/javascripts",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionview-7.0.4.3/lib/assets/compiled",
 #<Pathname:/Users/inabayasushiakira/portfolio/zuboramen/app/javascript>,
 #<Pathname:/Users/inabayasushiakira/portfolio/zuboramen/vendor/javascript>,
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/popper_js-2.11.7/assets/javascripts",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootstrap-5.2.3/assets/stylesheets",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootstrap-5.2.3/assets/javascripts"]
```

**Comment by yasu575** [comment]
すみません。再起動したら、追加されました

```
irb(main):001:0> Rails.applicat
ion.config.assets.paths
=> 
["/Users/inabayasushiakira/portfolio/zuboramen/app/assets/config",
 "/Users/inabayasushiakira/portfolio/zuboramen/app/assets/images",
 "/Users/inabayasushiakira/portfolio/zuboramen/app/assets/javascripts",
 "/Users/inabayasushiakira/portfolio/zuboramen/app/assets/stylesheets",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/jquery-rails-4.5.1/vendor/assets/javascripts",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/stimulus-rails-1.2.1/app/assets/javascripts",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/turbo-rails-1.4.0/app/assets/javascripts",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/importmap-rails-1.1.6/app/assets/javascripts",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actioncable-7.0.4.3/app/assets/javascripts",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actiontext-7.0.4.3/app/assets/javascripts",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actiontext-7.0.4.3/app/assets/stylesheets",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activestorage-7.0.4.3/app/assets/javascripts",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionview-7.0.4.3/lib/assets/compiled",
 #<Pathname:/Users/inabayasushiakira/portfolio/zuboramen/node_modules>,
 #<Pathname:/Users/inabayasushiakira/portfolio/zuboramen/app/javascript>,
 #<Pathname:/Users/inabayasushiakira/portfolio/zuboramen/vendor/javascript>,
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/popper_js-2.11.7/assets/javascripts",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootstrap-5.2.3/assets/stylesheets",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootstrap-5.2.3/assets/javascripts"]
```

**Comment by Tsuchiya2** [comment]
404 not foundが出なくなったということは、node_modules配下も読み込まれる状態になっていることだと思います。

インクリメンタルサーチができない要因は分かりかねますが、node_modules配下のファイルも無事読み込まれる状態になったので、公式ドキュメントや関連記事を参照して挑戦してみてください。

以下、別件になりますが、「マルチ検索・オートコンプリート」に関する情報になります。

---

■概要
食べログの検索フォームのような、様々なカラムから検索可能な検索フォームです。1文字入力するたびに、候補が表示されるため、ユーザーの入力手間を減らし、入力ミスを減らすことができます。

■使用技術・ライブラリ
Stimulus Autocomplete（Rails7 ）；https://github.com/afcapel/stimulus-autocomplete
JQuery；https://github.com/xpeppers/rails-autocomplete

**Comment by yasu575** [comment]
>取り敢えず、記載したJavaScriptが正しく動作するかconsole.logなどを使って確認するところから始めると良いかもです。

cosole.logを使ってディベロッパーツールに反映されているか確認をしてみましたが、反映されていませんでした。
やり方や記述場所がおかしくないかなどの確認をお願いしたいです。
記述場所ややり方がおかしくない場合、JavaScriptが正しく動作されていないということになると思うのですが、正しく動作させるためには、何の確認が必要になるのでしょうか？

select_controller.js

```
import { Controller } from "@hotwired/stimulus"
import TomSelect from "tom-select"

console.log('JavaScript');

// Connects to data-controller="select"
export default class extends Controller {
  connect() {
    new TomSelect('#select',{
      create: true,
      sortField: {
        field: "text",
        direction: "asc"
      },
    });
  }
}
```
下記がディベロッパーツールの内容です
[![Image from Gyazo](https://i.gyazo.com/8237f8aaf693f49ec5700319df538978.png)](https://gyazo.com/8237f8aaf693f49ec5700319df538978)


> 以下、別件になりますが、「マルチ検索・オートコンプリート」に関する情報になります。

こちらの情報はtom-selectとは違った、別の方法でインクリメンタルサーチを実装できるという捉え方でよろしいでしょうか？仮にこちらのやり方を使用する場合、tom-selectでやった内容は削除しておくのが適切ですか？

たくさんの質問や確認で申し訳ありません。お手数をおかけしますが、よろしくお願いします。

**Comment by Tsuchiya2** [comment]
まず共有した内容に関してはインクリメンタルサーチ以外で似たようなものを共有させていただきました。
もしそちらに切り替える際はtom-select関係で作成＆記載したものは削除しておきましょう。

console.log('JavaScript');

上記を記載しているのに、ブラウザの検証ツールのコンソールに"JavaScript"が表示されないということは、そもそもそのファイルは読み込まれていない可能性があります。select_controller.jsはマニフェストファイルに読み込まれるようになっているのか確認してみましょう。（console.logを使ったりしながら）

**Comment by yasu575** [comment]
>select_controller.jsはマニフェストファイルに読み込まれるようになっているのか確認してみましょう。（console.logを使ったりしながら）

どう確認したらいいですか？

マニフェストファイルは下記のようになっています
下記のファイルにconsole.log('JavaScript');を記載するとディベロッパーツールに表示されますが、app/javascript/controllers以下のファイル全てとapp/javascript/application.jsはconsole.log('JavaScript');を記載しても表示されませんでした。

```
[![Image from Gyazo](https://i.gyazo.com/df731990a0978455b5fc4104c250127b.png)](https://gyazo.com/df731990a0978455b5fc4104c250127b)
```

**Comment by Tsuchiya2** [comment]
`require_tree .`の記載は、同じディレクトリにあるJSファイルを読み込むというものです。

app/assets/javascripts/配下にhoge.jsを作成し、そこにconsole.logを書いてブラウザのコンソールに表示されるかを確認してみてください。表示されれば、同ディレクトリでのJSファイルが読み込まれていることが確認できます。

上記の方法でブラウザのターミナルに文字列が表示されるようであれば、hoge.jsに必要な記載を書いてみて、さらに期待している処理内にもconsole.log (A)を記載して、期待している挙動の箇所を動かした際に、(A)の文字列が表示されるか確認してみましょう。

**Comment by Tsuchiya2** [comment]
ピッタリな記事が見つけられませんでしたが、以下の記事などがマニフェストファイル・独自JSファイルの読み込みの参考になるかもです。
- https://papael14.com/ruby-on-rails-javascript/
- https://qiita.com/prgseek/items/bf77c44189c55a7b41d8

**Comment by yasu575** [comment]
> app/assets/javascripts/配下にhoge.jsを作成し、そこにconsole.logを書いてブラウザのコンソールに表示されるかを確認してみてください。

確認したところ、表示されました。

> 上記の方法でブラウザのターミナルに文字列が表示されるようであれば、hoge.jsに必要な記載を書いてみて、さらに期待している処理内にもconsole.log (A)を記載して、期待している挙動の箇所を動かした際に、(A)の文字列が表示されるか確認してみましょう。

hoge.jsに必要な記載を書くというのはselect_controller.js内のコードを書くということですか？
また、期待している処理内というのはselect_controller.js内ということでしょうか？

**Comment by Tsuchiya2** [comment]
そうですね。その認識で良いと思います。

また、今後のためのコメントになりますが、確認を求める前に手を動かして試行錯誤する癖付けをつけましょう。
開発の際に手順書のようなものは存在しないので、公式ドキュメント等を参考に試行錯誤しながら実装していくことになりますので、次回以降に関してはRUNTEQの質問フォームにある書式に従った内容でコメントをお願いいたします。

**Comment by yasu575** [comment]
- 質問内容・実現したいこと
app/javascript/controllers配下の記述が反映されるようにしたい

- 現状発生している問題・エラーメッセージ
hoge.jsに必要な記載を書き、console.log('JavaScript');を記載して、表示されるか確認したが、表示されなかった。
hoge.jsに必要な記載を書いたことで下記のエラーが新しくでてきた。

[![Image from Gyazo](https://i.gyazo.com/8a8e3ae8e190a3a4041561864cc50691.png)](https://gyazo.com/8a8e3ae8e190a3a4041561864cc50691)

- どの処理までうまく動いているのか
app/assets/javascripts/配下にhoge.jsを作成し、そこにconsole.logを書いてブラウザのコンソールに表示されるところまではうまく動いています。

- 該当のソースコード
app/assets/javascripts/hoge.js

```
console.log('JavaScript');
import { Controller } from "@hotwired/stimulus"
import TomSelect from "tom-select"
// Connects to data-controller="select"
export default class extends Controller {
  connect() {
    new TomSelect('#select',{
      plugins: ['dropdown_input'],
    });
  }   
}
```

- エラーから考えられる原因
モジュール外でimportステートメントを使用することが出来ませんというエラーがでており、この記載はapp/javascript/controllers配下でないと使えないのではないかと思いました。

- 試したこと
https://qiita.com/kazutosato/items/1ae1cf0ec380a75d4dc4
https://web-engineer-wiki.com/javascript/error-import-statement/
こちらの記事の内容を試してみましたが、うまくいきませんでした。

**Comment by Tsuchiya2** [comment]
まずはapp/javascript/controllers/配下のJSファイルが正しく読み込まれているか、hoge.jsのときと同様に検証してみてください。

次回の投稿も同様にお願いします。

---

以下ChatGPTに投げた結果の共有です。（万能ではないので言い切っていても期待通りの挙動にならないことがあるので注意してください）

Ruby on Rails 7ではJavaScriptのコンパイラとして、デフォルトでjsbundling-railsが導入されており、その中にesbuildが含まれています。esbuildは非常に高速なJavaScriptバンドラで、importステートメントもサポートしています。

あなたの問題について考えると、最初に考慮すべきはhoge.jsファイルの場所と、それが適切にバンドルされているかどうかです。esbuildを使用している場合、エントリポイントは通常app/javascriptディレクトリ内に配置されます。そして、そのエントリポイントから必要なJavaScriptファイルやモジュールをimportします。

あなたのコードを見ると、StimulusとTomSelectをimportしています。これらはnpmパッケージとしてあなたのプロジェクトにインストールされているでしょうか？もしインストールされていなければ、これらのimportステートメントはエラーを引き起こすでしょう。以下のようなコマンドでそれらのパッケージをインストールできます：

```
npm install @hotwired/stimulus
npm install tom-select
```

hoge.jsファイルをエントリポイントまたは他のエントリポイントから適切にインポートするようにesbuildを設定してください。そのためには、次のようなファイル構造が必要になるでしょう：

```
app/javascript/application.js
app/javascript/controllers/hoge_controller.js
```

application.jsには以下のように書くことで、hoge_controller.jsをインポートできます：
```
import "./controllers/hoge_controller.js"
```

そしてhoge_controller.jsには、質問にあるコードをそのまま書きます：
```
import { Controller } from "@hotwired/stimulus"
import TomSelect from "tom-select"

export default class extends Controller {
  connect() {
    new TomSelect('#select',{
      plugins: ['dropdown_input'],
    });
  }
}
```

以上を行うことで、あなたのhoge.jsファイルのコードが適切にバンドルされ、ブラウザで実行されるはずです。

----

**Comment by yasu575** [comment]
- 質問内容・実現したいこと
app/javascript/controllers配下の記述が反映されるようにしたい

- 現状発生している問題・エラーメッセージ
app/javascript/controllers配下の記述がブラウザに反映されない。

- どの処理までうまく動いているのか
app/assets/javascripts/配下にconsole.logを書いてブラウザのコンソールに表示されるのは確認できています。

- 該当のソースコード
app/javascripts/controllers/application.js

```
import { Application } from "@hotwired/stimulus"

const application = Application.start()

// Configure Stimulus development experience
application.debug = false
window.Stimulus   = application

export { application }
```

app/javascripts/controllers/hello_controller.js

```
import { Controller } from "@hotwired/stimulus"

export default class extends Controller {
  connect() {
    this.element.textContent = "Hello World!"
  }
}
```

app/javascripts/controllers/index.js

```
// Import and register all your controllers from the importmap under controllers/*

import { application } from "controllers/application"

import SelectController from "./select_controller"
application.register("select", SelectController) 
// Eager load all controllers defined in the import map under controllers/**/*_controller
import { eagerLoadControllersFrom } from "@hotwired/stimulus-loading"
eagerLoadControllersFrom("controllers", application)

// Lazy load controllers as they appear in the DOM (remember not to preload controllers in import map!)
// import { lazyLoadControllersFrom } from "@hotwired/stimulus-loading"
// lazyLoadControllersFrom("controllers", application)
```

app/javascripts/controllers/select_controller.js

```
import { Controller } from "@hotwired/stimulus"
import TomSelect from "tom-select"
// Connects to data-controller="select"
export default class extends Controller {
  connect() {
    new TomSelect('#select',{
      plugins: ['dropdown_input'],
    });
  }   
}
```

app/javascript/application.js

```
// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"
```

- 試したこと
app/javascript/controllers配下のJSファイルが正しく読み込まれているかconsole.logで確認したところ、表示されませんでした。
@hotwired/stimulusとtom-selectをyarn add ~　で入れていたが、npm で入れていなかったので、npm install @hotwired/stimulusとnpm install tom-selectを試しに入れてみましたが、変わらなかったです。
app/javascript/application.jsのコード内容が

```
import "@hotwired/turbo-rails"
import "controllers"
```

でimport "@hotwired/turbo-rails"がpackage.jsonになかったため、yarn add @hotwired/turbo-railsで入れたが、変わらず...。
import "controllers"の書き方もimport "./controllers/select_controller.js"にしてピンポイントで指定したが、うまくいきませんでした。

**Comment by Tsuchiya2** [comment]
そうですね。。。
質問の形は良くなりましたが、ご自身で実装するのために試行錯誤するという点では、あまり良くない相談になっていますね。

以下、今後開発現場に入った際に問題にならないための注意として受け止めていただけると幸いです。

---

■質問のフォーマットに沿っているものの、自分で実装するという意志が感じられない
「app/javascript/controllers配下のJSファイルが正しく読み込まれているかconsole.logで確認したところ、表示されませんでした。」とありますが、表示されるために何をどれだけ行ったのでしょうか？app/assets/javascript/配下にあるJSと、app/javascript/配下にあるJSがありますが、なぜディレクトリが分かれているのでしょうか？また、それぞれどこで読み込まれているか理解しようと調べたりしたことが伝わってこなかったので、只々他者に開発を投げているのと同じではないでしょうか？この開発を通じで力を付けることが目的の１つでもあるのに、それで良いのでしょうか？

---

その上でtom-selectを使ってのインクリメンタルサーチは実装が現状の技術力では難しいようですので、インクリメンタルサーチを実装するのなら、別の方法での実装を考えましょう。

以下のような記事を参考に頑張ってください。
- https://qiita.com/yoshi_4/items/d27a2306fe41dad4c713
- https://qiita.com/tochisuke221/items/fcc71432a165eed5ac11
- https://no-idea.hateblo.jp/entry/2020/08/09/170034

尚、確認依頼はせず、まずはご自身で調べたりして実装に取り組んでみてください。

**Comment by yasu575** [comment]
ご指摘ありがとうございます。
違う方法に切り替えて自分でもう一度、試行錯誤しながら実装に挑戦したいと思います。
ご迷惑をおかけして、申し訳ありませんでした。
