### ISSUE TITLE
heroku上でjqueryを機能させたい

### ISSUE THREAD

**Issue by yasu575** [yasu575/zuboramen#66]
- 質問内容・実現したいこと
heroku上でjqueryが機能しない

- 現状発生している問題・エラーメッセージ
ログアウトした際に、下記のエラーが発生してしまいます。
[![Image from Gyazo](https://i.gyazo.com/1712a56c8815cf42de9c6e854d6999b4.png)](https://gyazo.com/1712a56c8815cf42de9c6e854d6999b4)

- どの処理までうまく動いているのか
ローカル環境では、jqueryが反映されており、ログアウトできます。

- 該当のソースコード
routes.rb
```
Rails.application.routes.draw do
  root 'static_pages#top'
  get 'terms', to: 'static_pages#terms'
  get 'privacy', to: 'static_pages#privacy'
  get 'contact', to: 'static_pages#contact'
  
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :users, only: %i[new create]

  resources :posts do
    collection do
      get :likes
    end
  end

  resources :toppings do
    get 'posts', to: 'posts#search'
  end

  resources :likes, only: %i[create destroy]
  resource :profile, only: %i[show edit update]
end
```

app/views/shared/_header.html.erb
```
<li class="nav-item">
   <%= link_to t('defaults.logout'), logout_path, class: 'nav-link text-dark fw-bold', method: :delete %>
</li>
```

app/controllers/user_sessions_controller.rb
```
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  
  def new
  end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_back_or_to root_path, success: t('.success')
    else
      flash.now[:danger] = t('.fail')
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path, success: t('.success')
  end
end
```

app/assets/javascripts/application.js
```
//= require rails-ujs
//= require jquery3
//= require popper
//= require bootstrap-sprockets
//= require_tree .
```

Gemfile
```
gem "bootstrap", "~> 5.2.3"
gem "jquery-rails"
```

- エラーから考えられる原因
最初は、ルーティング周りのコード記載に誤りがあるかと思い、確認しましたが、おかしいところはなく、ローカル環境で試してみてもうまく機能していたので、jqueryが反映されておらず、ログアウトができていないと考えられます。rails7になってからjsあたりが前のバージョンから変更されているのも原因がありそう。

- 試したこと
rails cでRails.application.config.assets.pathsを確認しましたが、jqueryが含まれていることを確認。

```
irb(main):001:0> Rails.application.config.assets.paths
=> 
["/Users/inabayasushiakira/portfolio/zuboramen/app/assets/builds",
 "/Users/inabayasushiakira/portfolio/zuboramen/app/assets/config",
 "/Users/inabayasushiakira/portfolio/zuboramen/app/assets/images",
 "/Users/inabayasushiakira/portfolio/zuboramen/app/assets/javascripts",
 "/Users/inabayasushiakira/portfolio/zuboramen/app/assets/stylesheets",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/jquery-rails-4.5.1/vendor/assets/javascripts",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/stimulus-rails-1.2.1/app/assets/javascripts",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/turbo-rails-1.4.0/app/assets/javascripts",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/importmap-rails-1.1.6/app/assets/javascripts",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actioncable-7.0.4.3/app/assets/javascripts",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actiontext-7.0.4.3/app/assets/javascripts",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actiontext-7.0.4.3/app/assets/stylesheets",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activestorage-7.0.4.3/app/assets/javascripts",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionview-7.0.4.3/lib/assets/compiled",
 #<Pathname:/Users/inabayasushiakira/portfolio/zuboramen/app/javascript>,
 #<Pathname:/Users/inabayasushiakira/portfolio/zuboramen/vendor/javascript>,
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/popper_js-2.11.7/assets/javascripts",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootstrap-5.2.3/assets/stylesheets",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootstrap-5.2.3/assets/javascripts"]
```

yarn add jqueryを実行し、yarnでjqueryを入れてみたが、うまくいかず、下記の記事を見てrailsのアセットをプリコンパイルするため、
```
bundle exec rake assets:precompile RAILS_ENV=production
```
しましたが、変わりませんでした。

- 参考記事
https://qiita.com/tukinasikotonoha/items/1c487f08365ef864490b
https://www.amelt.net/imc/programming/rails/4913/
https://qiita.com/rubyist_yasunao/items/fd0840963df962a2063b

**Comment by Tsuchiya2** [comment]
Rails7系からturboが標準になっています。
以下の記事とか参考にしてみてください。
https://picolab.dev/2022/03/23/rails7-turbo/

上記の情報だけでは判断できないので、エラー画面が出てしまった際のログ（前後含む）を確認して状況を確認してみてください。

**Comment by yasu575** [comment]
- 質問内容・実現したいこと
jqueryが機能しなくなった

- 現状発生している問題・エラーメッセージ
ログアウトした際に、下記のようなエラーが発生しており、
```
ActionController::RoutingError (No route matches [GET] "/logout"):
```
rails routesでルーティングを確認したらlogout GET    /logout(.:format)  となっており、
routes.rbのログアウトの記載を下記のようにdeleteからgetに変更したらログアウトできるようになりました。
```
get 'logout', to: 'user_sessions#destroy'
```
しかし、なぜgetに変わってしまっていたのか疑問に思い、いろいろなサイトを調べてみると、jsの問題みたいでした。js周りの確認をしようと、app/assets/javascripts/application.jsに
```
console.log("hoge");
```
を記載し、ディベロッパーツールで確認したら、表示されなかったため、jsが動いていないのではないかと推測しました。また、確認も込めていいね機能でjsを使用していたので確認したら
```
Routing Error
No route matches [GET] "/likes"
```
とエラーが発生し、jsを使用している部分だけ、エラーが発生してしまうようになっていました。

 https://teratail.com/questions/3n8ry8tlygeg2i                         

- どの処理までうまく動いているのか
ルーティングをdeleteからgetに変更したらログアウトできます

- 該当のソースコード
app/assets/javascripts/application.js
```
//= require rails-ujs
//= require jquery3
//= require popper
//= require bootstrap-sprockets
//= require_tree .
```

- エラーから考えられる原因
インクリメンタルサーチの実装からyarnでいろいろなパッケージをインストールしたり、消したりを繰り返しており、それが混乱してjsが反映されなくなっていったのではないかと思いました。

- 試したこと
>Rails7系からturboが標準になっています。
以下の記事とか参考にしてみてください。
https://picolab.dev/2022/03/23/rails7-turbo/
上記の情報だけでは判断できないので、エラー画面が出てしまった際のログ（前後含む）を確認して状況を確認してみてください。

まず最初は、アドバイス通り確認して試してみましたが、うまくいかず、エラーログを確認し、下記の参考記事を試しました。
https://teratail.com/questions/291155
https://qiita.com/vinaka/items/ba0c8fd9b9fa76bf0010
https://teratail.com/questions/256667
https://qiita.com/kazutosato/items/1ae1cf0ec380a75d4dc4

その後もyarn add jquery bootstrap popper.jsを打ち込んだり、gemfileのgem "bootstrap", "~> 5.2.3"とgem "jquery-rails"を入れ直したり、試しすぎておかしくなってしまったのかと思いました。yarn add ~で入れては消してを繰り返したり、yarnのファイルを消したり、package.jsonを消したりnode_moduleをファイルを消したり色々といじりすぎて取り返しのつかないことになってしまったのかもしれません。

この辺りでrails routesを確認してlogoutのルーティングがdeleteではなく、getに変わっていることに気がつきました。

rails cでRails.application.config.assets.pathsを確認しましたが、これまで含まれていたjqueryが消えてしまっていました。

```
irb(main):001:0> Rails.application.config.assets.paths
=> 
["/Users/inabayasushiakira/portfolio/zuboramen/app/assets/builds",
 "/Users/inabayasushiakira/portfolio/zuboramen/app/assets/config",
 "/Users/inabayasushiakira/portfolio/zuboramen/app/assets/images",
 "/Users/inabayasushiakira/portfolio/zuboramen/app/assets/javascripts",
 "/Users/inabayasushiakira/portfolio/zuboramen/app/assets/stylesheets",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/jquery-rails-4.5.1/vendor/assets/javascripts",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/stimulus-rails-1.2.1/app/assets/javascripts",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/turbo-rails-1.4.0/app/assets/javascripts",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/importmap-rails-1.1.6/app/assets/javascripts",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actioncable-7.0.4.3/app/assets/javascripts",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actiontext-7.0.4.3/app/assets/javascripts",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actiontext-7.0.4.3/app/assets/stylesheets",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activestorage-7.0.4.3/app/assets/javascripts",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/actionview-7.0.4.3/lib/assets/compiled",
 #<Pathname:/Users/inabayasushiakira/portfolio/zuboramen/app/javascript>,
 #<Pathname:/Users/inabayasushiakira/portfolio/zuboramen/vendor/javascript>,
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/popper_js-2.11.7/assets/javascripts",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootstrap-5.2.3/assets/stylesheets",
 "/Users/inabayasushiakira/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootstrap-5.2.3/assets/javascripts"]
```

なぜjqueryが機能しなくなってしまったのかの原因が突き止められず、停滞してしまっています。アドバイスをお願いしたいです。よろしくお願いします。

- 参考記事
https://teratail.com/questions/3n8ry8tlygeg2i
https://teratail.com/questions/291155
https://qiita.com/vinaka/items/ba0c8fd9b9fa76bf0010
https://teratail.com/questions/256667
https://qiita.com/kazutosato/items/1ae1cf0ec380a75d4dc4
https://magazine.techacademy.jp/magazine/41310
https://qiita.com/Akari71/items/8b64d615326a195e160e

**Comment by Tsuchiya2** [comment]
Rails7系だとlink_toのHTTPメソッドを指定する際の書き方が変わっていますが、その辺はちゃんと記載できていますでしょうか？以下の指定の方法はRails6系までですので確認してみましょう。

```
method: :delete
```

参考：https://qiita.com/sijiaoh/items/973f9f7d91d669a79ef5

**Comment by yasu575** [comment]
```
<%= link_to t('defaults.logout'), logout_path, class: 'nav-link text-dark fw-bold', data: { turbo_method: :delete } %>
```
で試してみたのですが、うまくいかなかったため、turboについて調べ、下記の記事を参考に
https://note.com/everyleaf/n/n0a5934373f12

application.js を見る、Importmapを確認、rails console を使って確認をしました。
config/importmap.rbを間違えて消してゴミ箱から戻したからimportmapの記載が反映されていないと思い、
```
rails importmap:install
```
で入れ直し、元々あったコードを記載したところ、ログアウトできるようになりました。
rails routesでルーティングを確認しても
```
logout DELETE /logout(.:format)                                            
```
とGETからDELETEに変わっていました。

アドバイスありがとうございました。
