### ISSUE TITLE
MVPリリースレビュー

### ISSUE THREAD

**Issue by Tsuchiya2** [yasu575/zuboramen#67]
ご提出ありがとうございます。
以下の観点からレビューを行います。

1. READMEから課題解決する実装がされているか&動いている
2. 静的コードチェックが入っている
3. 就活において十分な技術力を示せる機能を実装しているか
4. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか

---

#### 1について
画像付きで投稿できるのを確認しました。タグ・検索も確認しました。

#### 2について
Rubocopを使って指摘箇所を修正するようにしましょう。

#### 3について
印象としましてはCRUD+αアプリな印象を受けました。
以下の機能を追加を検討してみてください。

■レコメンド
概要：投稿されたまたは事前に用意されたコンテンツと類似したコンテンツを推奨する機能をレコメンドと呼びます。代表的なアルゴリズムとして、協調フィルタリングとコンテンツフィルタリングがあります。協調フィルタリングは、ユーザの行動や嗜好データを元に類似度を算出し、コンテンツベースフィルタリングは、コンテンツの数値化された特徴や評価を元に類似度を算出します。
使用技術・ライブラリ：
- Amazon Personalize
  - https://docs.aws.amazon.com/ja_jp/personalize/latest/dg/what-is-personalize.html
  - AWSが提供する機械学習の知識がなくても、個々のユーザー向けにリコメンデーションをリアルタイムで提供できるサービスです。
- GCP Recommendations AI
  - https://cloud.google.com/recommendations?hl=ja
  - Recommendations AIは、Google Cloud Platformが提供するレコメンドエンジンであり、Googleの機械学習アルゴリズムを利用しています。
- アルゴリズム
  - 協調フィルタリングやコンテンツベースフィルタリングは、一般的にアルゴリズムが公開されているので、RubyやPythonで独自に実装することも可能です。

■チャット
概要：FacebookメッセンジャーやSNSなどには、チャット機能が必ずついています。現在では、WebSocketを用いることで、リアルタイムでやり取りが可能となっています。コツさえ掴めば、比較的簡単に実装できます。ダイレクトメッセージのようなチャット機能を実装することで、ユーザー同士のコミュニケーションを活性化させることができるかもしれません。
使用技術・ライブラリ：
- WebSocket
  - https://ja.wikipedia.org/wiki/WebSocket
- ActionCable（Rails標準）
  - https://railsguides.jp/action_cable_overview.html

#### 4について
- ログイン前に利用規約などにアクセスすると「ログインしてください」といったフラッシュメッセージが出ていました。
- 対象の麺を探すのが大変＆途中で諦めたくなりました。この部分は改善が必要かと思います。
- ログイン後の右上に表示されるアイコン部分は何をするためのものか、良く分からなかったです。（クリックしてプロフィール編集等ができるかと思ってしまいました）
- ドメインは独自ドメインを用意しましょう。

**Comment by Tsuchiya2** [comment]
--- 質問 ---
本リリースまでに追加する機能を箇条書きにしてください。
また、本リリースがいつになるのかもお答えください。

**Comment by yasu575** [comment]
レビューありがとうございます。
指摘箇所、改善していきたいと思います。

## 本リリースまでに追加する機能
・トップページに使い方などの概要追加
・お気に入り機能
・コメント機能
・ランキング機能
・レコメンド機能

## 本リリース
7月末を予定しています

**Comment by Tsuchiya2** [comment]
ご返答ありがとうございます。
引き続き開発頑張ってください。
